version: '2.1'
services:
    mysql_magento:
        image: 'mariadb:10.2'
        environment:
            - MYSQL_ROOT_PASSWORD=magento2
            - MYSQL_DATABASE=magento2
            - MYSQL_USER=magento2
            - MYSQL_PASSWORD=magento2
        ports:
            - '3306'
        volumes:
            - '.docker/mysql/:/var/lib/mysql'
        healthcheck:
            test: 'mysqladmin ping -h localhost'
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            magento:
                aliases:
                    - mysql_magento
    elasticsearch_magento:
        image: markoshust/magento-elasticsearch:7.6.2-2
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - "discovery.type=single-node"
        networks:
            magento:
                aliases:
                    - elasticsearch_magento
    nginx_magento:
        image: 'markoshust/magento-nginx:1.18-4'
        ports:
            - '80:8000'
            - '443:8443'
        volumes: &appvolumes
            - ./:/var/www/html:cached
            - ./.docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/etc/conf.d/:/etc/nginx/conf.d/
            - ./.docker/nginx/log/:/var/log/nginx/
            - sockdata:/sock
        networks:
            magento:
                aliases:
                    - nginx_magento
        depends_on:
            php_magento:
                condition: service_started

    php_magento:
        image: 'markoshust/magento-php:7.4-fpm'
        volumes: *appvolumes
        networks:
            magento:
                aliases:
                    - php_magento
        depends_on:
            mysql_magento:
                condition: service_healthy
    redis_magento:
        image: redis:5.0-alpine
        networks:
            magento:
                aliases:
                    - redis_magento

networks:
    magento:
        driver: bridge

volumes:
    sockdata:
